name: slimy_card_plus
description: It provides a beautiful slime-like animation of a Card that separates into two.
version: 1.0.5
homepage: https://github.com/zhangyc/SlimyCard-Animated-Flutter-Package.git

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flare_flutter:
    git:
      url: https://github.com/mbfakourii/Flare-Flutter.git
      path: flare_flutter
      ref: remove_hashValues


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/flare/
